//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCheckout
    {
        public int Id { get; set; }
        public int bookingIdFk { get; set; }
        public System.DateTime checkoutDate { get; set; }
    
        public virtual StaffBooking StaffBooking { get; set; }
    }
}
