//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffBooking()
        {
            this.ClientCheckouts = new HashSet<ClientCheckout>();
        }
    
        public int Id { get; set; }
        public int roomId { get; set; }
        public int customerId { get; set; }
        public Nullable<bool> status { get; set; }
        public System.DateTime checkInDate { get; set; }
        public System.DateTime checkOutDate { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCheckout> ClientCheckouts { get; set; }
    }
}
